/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.villabeef.view;

import com.villabeef.model.dto.Funcionario;
import com.villabeef.model.service.ManterFuncionario;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Funcionarios1 extends javax.swing.JFrame {
    
    DefaultTableCellRenderer renderer = null;
    
    DefaultTableModel modelo = null;
    
    private int mouseX, mouseY;
    /**
     * Creates new form Funcionarios1
     */
    public Funcionarios1() {
        initComponents();
        
        scrollPane.getViewport().setBackground(new Color(245, 222, 179));
        scrollPane.getViewport().setBorder(null);
        
        tabela.getTableHeader().setFont(new Font("Arial", Font.BOLD, 18));
        tabela.getTableHeader().setOpaque(false);
        tabela.getTableHeader().setBackground(new Color(76, 21, 32));
        tabela.getTableHeader().setForeground(new Color(245, 222, 179));
        tabela.setRowHeight(25);
        
        modelo = (DefaultTableModel) tabela.getModel();
        
        try {
            atualizarTabela(ManterFuncionario.listar());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Falha na conexão com o banco de dados.", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void atualizarTabela(HashSet<Funcionario> lista) {
        
        DecimalFormat formato = new DecimalFormat("0.00");
        
        if (modelo != null) {
            modelo.getDataVector().removeAllElements();
            modelo.fireTableDataChanged();
        }

        for (Funcionario funcionario : lista) {
            modelo.insertRow(modelo.getRowCount(), new Object[] {funcionario.getId(), 
            funcionario.getNome(), funcionario.getFuncao(), "R$ " + formato.format(funcionario.getSalario())});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        nomeIcone = new javax.swing.JLabel();
        fecharButton = new javax.swing.JPanel();
        fecharTxt = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        contaBancaria = new javax.swing.JLabel();
        identificacao = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        funcao = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        identificacaoCampo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        funcaoCampo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        contaBancariaCampo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        buscaTxt = new javax.swing.JTextField();
        buscaButton = new javax.swing.JPanel();
        buscaIcon = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        editarButton = new javax.swing.JPanel();
        editarTxt = new javax.swing.JLabel();
        aplicarButton = new javax.swing.JPanel();
        aplicarTxt = new javax.swing.JLabel();
        limparButton = new javax.swing.JPanel();
        limparTxt = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JPanel();
        cadastrarTxt = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        salarioCampo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 580));
        setMinimumSize(new java.awt.Dimension(900, 580));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 580));
        setResizable(false);

        background.setBackground(new java.awt.Color(245, 222, 179));
        background.setMaximumSize(new java.awt.Dimension(900, 580));
        background.setMinimumSize(new java.awt.Dimension(900, 580));
        background.setPreferredSize(new java.awt.Dimension(900, 580));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(76, 21, 32));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VILLAsmall.png"))); // NOI18N
        nomeIcone.setText("jLabel2");
        header.add(nomeIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 5, 100, -1));

        fecharButton.setBackground(header.getBackground());

        fecharTxt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fecharTxt.setForeground(background.getBackground());
        fecharTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecharTxt.setText("X");
        fecharTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        fecharTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fecharTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fecharTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fecharButtonLayout = new javax.swing.GroupLayout(fecharButton);
        fecharButton.setLayout(fecharButtonLayout);
        fecharButtonLayout.setHorizontalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fecharButtonLayout.setVerticalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(fecharButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        tabela.setBackground(header.getBackground());
        tabela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(220, 184, 153));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificação", "Nome", "Função", "Salário"
            }
        ));
        tabela.setGridColor(new java.awt.Color(204, 204, 204));
        tabela.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabela.setRowHeight(25);
        tabela.setSelectionBackground(new java.awt.Color(119, 34, 51));
        tabela.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabela.setShowGrid(true);
        tabela.setShowVerticalLines(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tabela);

        background.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 480, 450));

        contaBancaria.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contaBancaria.setForeground(header.getBackground());
        contaBancaria.setText("CONTA BANCÁRIA");
        background.add(contaBancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        identificacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        identificacao.setForeground(header.getBackground());
        identificacao.setText("IDENTIFICAÇÃO");
        background.add(identificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        nome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nome.setForeground(header.getBackground());
        nome.setText("NOME");
        background.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        funcao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        funcao.setForeground(header.getBackground());
        funcao.setText("FUNÇÃO");
        background.add(funcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        nomeCampo.setBackground(background.getBackground());
        nomeCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomeCampo.setForeground(new java.awt.Color(0, 0, 0));
        nomeCampo.setText("Selecione um funcionário para inspecioná-lo");
        nomeCampo.setToolTipText("");
        nomeCampo.setBorder(null);
        nomeCampo.setDisabledTextColor(java.awt.Color.gray);
        nomeCampo.setEnabled(false);
        nomeCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeCampoFocusLost(evt);
            }
        });
        background.add(nomeCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 320, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 320, 10));

        identificacaoCampo.setBackground(background.getBackground());
        identificacaoCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        identificacaoCampo.setForeground(new java.awt.Color(0, 0, 0));
        identificacaoCampo.setText("Selecione um funcionário para inspecioná-lo");
        identificacaoCampo.setToolTipText("");
        identificacaoCampo.setBorder(null);
        identificacaoCampo.setDisabledTextColor(java.awt.Color.gray);
        identificacaoCampo.setEnabled(false);
        identificacaoCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                identificacaoCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                identificacaoCampoFocusLost(evt);
            }
        });
        background.add(identificacaoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 320, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 320, 10));

        funcaoCampo.setBackground(background.getBackground());
        funcaoCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        funcaoCampo.setForeground(new java.awt.Color(0, 0, 0));
        funcaoCampo.setText("Selecione um funcionário para inspecioná-lo");
        funcaoCampo.setToolTipText("");
        funcaoCampo.setBorder(null);
        funcaoCampo.setDisabledTextColor(java.awt.Color.gray);
        funcaoCampo.setEnabled(false);
        funcaoCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                funcaoCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                funcaoCampoFocusLost(evt);
            }
        });
        background.add(funcaoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 320, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 320, 10));

        contaBancariaCampo.setBackground(background.getBackground());
        contaBancariaCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contaBancariaCampo.setForeground(new java.awt.Color(0, 0, 0));
        contaBancariaCampo.setText("Selecione um funcionário para inspecioná-lo");
        contaBancariaCampo.setToolTipText("");
        contaBancariaCampo.setBorder(null);
        contaBancariaCampo.setDisabledTextColor(java.awt.Color.gray);
        contaBancariaCampo.setEnabled(false);
        contaBancariaCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contaBancariaCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contaBancariaCampoFocusLost(evt);
            }
        });
        background.add(contaBancariaCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 320, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 320, 10));

        buscaTxt.setBackground(background.getBackground());
        buscaTxt.setForeground(java.awt.Color.gray);
        buscaTxt.setText("Busca");
        buscaTxt.setBorder(null);
        buscaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscaTxtFocusLost(evt);
            }
        });
        background.add(buscaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 430, 40));

        buscaButton.setBackground(background.getBackground());

        buscaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busca.png"))); // NOI18N
        buscaIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout buscaButtonLayout = new javax.swing.GroupLayout(buscaButton);
        buscaButton.setLayout(buscaButtonLayout);
        buscaButtonLayout.setHorizontalGroup(
            buscaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscaButtonLayout.createSequentialGroup()
                .addComponent(buscaIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buscaButtonLayout.setVerticalGroup(
            buscaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(buscaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 430, 10));

        editarButton.setBackground(new java.awt.Color(59, 21, 32));
        editarButton.setEnabled(false);

        editarTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        editarTxt.setForeground(new java.awt.Color(102, 102, 102));
        editarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarTxt.setText("EDITAR");
        editarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarTxt.setEnabled(false);
        editarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editarButtonLayout = new javax.swing.GroupLayout(editarButton);
        editarButton.setLayout(editarButtonLayout);
        editarButtonLayout.setHorizontalGroup(
            editarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        editarButtonLayout.setVerticalGroup(
            editarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 100, 40));

        aplicarButton.setBackground(new java.awt.Color(59, 21, 32));
        aplicarButton.setEnabled(false);

        aplicarTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aplicarTxt.setForeground(new java.awt.Color(102, 102, 102));
        aplicarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aplicarTxt.setText("APLICAR");
        aplicarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aplicarTxt.setEnabled(false);

        javax.swing.GroupLayout aplicarButtonLayout = new javax.swing.GroupLayout(aplicarButton);
        aplicarButton.setLayout(aplicarButtonLayout);
        aplicarButtonLayout.setHorizontalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        aplicarButtonLayout.setVerticalGroup(
            aplicarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aplicarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(aplicarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 100, 40));

        limparButton.setBackground(new java.awt.Color(59, 21, 32));
        limparButton.setEnabled(false);

        limparTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limparTxt.setForeground(new java.awt.Color(102, 102, 102));
        limparTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limparTxt.setText("LIMPAR");
        limparTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limparTxt.setEnabled(false);
        limparTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout limparButtonLayout = new javax.swing.GroupLayout(limparButton);
        limparButton.setLayout(limparButtonLayout);
        limparButtonLayout.setHorizontalGroup(
            limparButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limparTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        limparButtonLayout.setVerticalGroup(
            limparButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limparTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(limparButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 100, 40));

        cadastrarButton.setBackground(header.getBackground());

        cadastrarTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarTxt.setText("CADASTRAR");
        cadastrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cadastrarButtonLayout = new javax.swing.GroupLayout(cadastrarButton);
        cadastrarButton.setLayout(cadastrarButtonLayout);
        cadastrarButtonLayout.setHorizontalGroup(
            cadastrarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        cadastrarButtonLayout.setVerticalGroup(
            cadastrarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 140, 40));

        salario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salario.setForeground(header.getBackground());
        salario.setText("SALÁRIO");
        background.add(salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        salarioCampo.setBackground(background.getBackground());
        salarioCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salarioCampo.setForeground(new java.awt.Color(0, 0, 0));
        salarioCampo.setText("Selecione um funcionário para inspecioná-lo");
        salarioCampo.setToolTipText("");
        salarioCampo.setBorder(null);
        salarioCampo.setDisabledTextColor(java.awt.Color.gray);
        salarioCampo.setEnabled(false);
        salarioCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salarioCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salarioCampoFocusLost(evt);
            }
        });
        background.add(salarioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 320, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 320, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_fecharTxtMouseClicked

    private void fecharTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseEntered
        fecharButton.setBackground(background.getBackground());
        fecharTxt.setForeground(header.getBackground());
    }//GEN-LAST:event_fecharTxtMouseEntered

    private void fecharTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseExited
        fecharButton.setBackground(header.getBackground());
        fecharTxt.setForeground(background.getBackground());
    }//GEN-LAST:event_fecharTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void nomeCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeCampoFocusGained
        if(nomeCampo.getText().equals("Selecione um funcionário para inspecioná-lo")) {
            nomeCampo.setText("");
            nomeCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_nomeCampoFocusGained

    private void identificacaoCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_identificacaoCampoFocusGained
        if(identificacaoCampo.getText().equals("Selecione um funcionário para inspecioná-lo")) {
            identificacaoCampo.setText("");
            identificacaoCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_identificacaoCampoFocusGained

    private void funcaoCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_funcaoCampoFocusGained
        if(funcaoCampo.getText().equals("Selecione um funcionário para inspecioná-lo")) {
            funcaoCampo.setText("");
            funcaoCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_funcaoCampoFocusGained

    private void contaBancariaCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaBancariaCampoFocusGained
        if(contaBancariaCampo.getText().equals("Selecione um funcionário para inspecioná-lo")) {
            contaBancariaCampo.setText("");
            contaBancariaCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_contaBancariaCampoFocusGained

    private void buscaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscaTxtFocusGained
        if(buscaTxt.getText().equals("Busca")) {
            buscaTxt.setText("");
            buscaTxt.setForeground(Color.black);
        }   
    }//GEN-LAST:event_buscaTxtFocusGained

    private void buscaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscaTxtFocusLost
        if(buscaTxt.getText().isBlank()) {
            buscaTxt.setText("Busca");
            buscaTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_buscaTxtFocusLost

    private void identificacaoCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_identificacaoCampoFocusLost
        if(identificacaoCampo.getText().isBlank()) {
            identificacaoCampo.setText("Selecione um funcionário para inspecioná-lo");
            identificacaoCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_identificacaoCampoFocusLost

    private void nomeCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeCampoFocusLost
        if(nomeCampo.getText().isBlank()) {
            nomeCampo.setText("Selecione um funcionário para inspecioná-lo");
            nomeCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nomeCampoFocusLost

    private void funcaoCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_funcaoCampoFocusLost
        if(funcaoCampo.getText().isBlank()) {
            funcaoCampo.setText("Selecione um funcionário para inspecioná-lo");
            funcaoCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_funcaoCampoFocusLost

    private void contaBancariaCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contaBancariaCampoFocusLost
        if(contaBancariaCampo.getText().isBlank()) {
            contaBancariaCampo.setText("Selecione um funcionário para inspecioná-lo");
            contaBancariaCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_contaBancariaCampoFocusLost

    private void cadastrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarTxtMouseClicked
        CadastroFuncionario c = new CadastroFuncionario(this, true);
        c.setVisible(rootPaneCheckingEnabled);
        c.setLocationRelativeTo(null);
        
        try {
            atualizarTabela(ManterFuncionario.listar());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Falha na conexão com o banco de dados.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarTxtMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        try {
            int index = tabela.getSelectedRow();
            
            TableModel modelo = tabela.getModel();
            
            Funcionario funcionario = ManterFuncionario.obterPorId(modelo.getValueAt(index, 0).toString());
            
            DecimalFormat formato = new DecimalFormat("0.00");
            
            identificacaoCampo.setText(funcionario.getId());
            nomeCampo.setText(funcionario.getNome());
            funcaoCampo.setText(funcionario.getFuncao());
            salarioCampo.setText(formato.format(funcionario.getSalario()));
            contaBancariaCampo.setText(funcionario.getConta());
            
            editarButton.setEnabled(true);
            editarButton.setBackground(header.getBackground());
            editarTxt.setEnabled(true);
            editarTxt.setForeground(Color.white);
            editarTxt.setCursor(new Cursor(Cursor.HAND_CURSOR));

            limparButton.setEnabled(true);
            limparButton.setBackground(header.getBackground());
            limparTxt.setEnabled(true);
            limparTxt.setForeground(Color.white);
            aplicarTxt.setCursor(new Cursor(Cursor.HAND_CURSOR));
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Falha na conexão com o banco de dados.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void salarioCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarioCampoFocusGained
        if(salarioCampo.getText().equals("Selecione um funcionário para inspecioná-lo")) {
            salarioCampo.setText("");
            salarioCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_salarioCampoFocusGained

    private void salarioCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salarioCampoFocusLost
        if(salarioCampo.getText().isBlank()) {
            salarioCampo.setText("Selecione um funcionário para inspecioná-lo");
            salarioCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_salarioCampoFocusLost

    private void limparTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparTxtMouseClicked
        identificacaoCampo.setText("Selecione um funcionário para inspecioná-lo");
        nomeCampo.setText("Selecione um funcionário para inspecioná-lo");
        funcaoCampo.setText("Selecione um funcionário para inspecioná-lo");
        salarioCampo.setText("Selecione um funcionário para inspecioná-lo");
        contaBancariaCampo.setText("Selecione um funcionário para inspecioná-lo");
        
        editarButton.setEnabled(false);
        editarButton.setBackground(new Color(59, 21, 32));
        editarTxt.setEnabled(false);
        editarTxt.setForeground(new Color(102, 102, 102));
        editarTxt.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        aplicarButton.setEnabled(false);
        aplicarButton.setBackground(new Color(59, 21, 32));
        aplicarTxt.setEnabled(false);
        aplicarTxt.setForeground(new Color(102, 102, 102));
        aplicarTxt.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        limparButton.setEnabled(false);
        limparButton.setBackground(new Color(59, 21, 32));
        limparTxt.setEnabled(false);
        limparTxt.setForeground(new Color(102, 102, 102));
        limparTxt.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        identificacaoCampo.setEnabled(false);
        nomeCampo.setEnabled(false);
        funcaoCampo.setEnabled(false);
        salarioCampo.setEnabled(false);
        contaBancariaCampo.setEnabled(false);
    }//GEN-LAST:event_limparTxtMouseClicked

    private void editarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseClicked
        aplicarButton.setEnabled(true);
        aplicarButton.setBackground(header.getBackground());
        aplicarTxt.setEnabled(true);
        aplicarTxt.setForeground(Color.white);
        aplicarTxt.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        identificacaoCampo.setEnabled(true);
        nomeCampo.setEnabled(true);
        funcaoCampo.setEnabled(true);
        salarioCampo.setEnabled(true);
        contaBancariaCampo.setEnabled(true);
    }//GEN-LAST:event_editarTxtMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios1().setVisible(true);
            }
        });
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aplicarButton;
    private javax.swing.JLabel aplicarTxt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel buscaButton;
    private javax.swing.JLabel buscaIcon;
    private javax.swing.JTextField buscaTxt;
    private javax.swing.JPanel cadastrarButton;
    private javax.swing.JLabel cadastrarTxt;
    private javax.swing.JLabel contaBancaria;
    private javax.swing.JTextField contaBancariaCampo;
    private javax.swing.JPanel editarButton;
    private javax.swing.JLabel editarTxt;
    private javax.swing.JPanel fecharButton;
    private javax.swing.JLabel fecharTxt;
    private javax.swing.JLabel funcao;
    private javax.swing.JTextField funcaoCampo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel identificacao;
    private javax.swing.JTextField identificacaoCampo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel limparButton;
    private javax.swing.JLabel limparTxt;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JLabel nomeIcone;
    private javax.swing.JLabel salario;
    private javax.swing.JTextField salarioCampo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 
}
