/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.villabeef.view;

import java.awt.Color;

/**
 *
 * @author chsdi
 */
public class MenuGerencia extends javax.swing.JFrame {
    
    private int mouseX, mouseY;
    
    
    /**
     * Creates new form MenuGerencia1
     */
    public MenuGerencia() {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        nomeIcone = new javax.swing.JLabel();
        fecharButton = new javax.swing.JPanel();
        fecharTxt = new javax.swing.JLabel();
        logoutButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rentabilidadeButton = new javax.swing.JPanel();
        rentabilidadeIcon = new javax.swing.JLabel();
        rentabilidadeTxt = new javax.swing.JLabel();
        estoqueButton = new javax.swing.JPanel();
        estoqueIcon = new javax.swing.JLabel();
        estoqueTxt = new javax.swing.JLabel();
        funcionariosButton = new javax.swing.JPanel();
        funcionariosIcon = new javax.swing.JLabel();
        funcionariosTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(245, 222, 179));
        background.setMaximumSize(new java.awt.Dimension(900, 500));
        background.setMinimumSize(new java.awt.Dimension(900, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(76, 21, 32));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VILLAsmall.png"))); // NOI18N
        nomeIcone.setText("jLabel2");
        header.add(nomeIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 5, 100, -1));

        fecharButton.setBackground(header.getBackground());

        fecharTxt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fecharTxt.setForeground(background.getBackground());
        fecharTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecharTxt.setText("X");
        fecharTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        fecharTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fecharTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fecharTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fecharButtonLayout = new javax.swing.GroupLayout(fecharButton);
        fecharButton.setLayout(fecharButtonLayout);
        fecharButtonLayout.setHorizontalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fecharButtonLayout.setVerticalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(fecharButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        logoutButton.setBackground(header.getBackground());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutB.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutButtonLayout = new javax.swing.GroupLayout(logoutButton);
        logoutButton.setLayout(logoutButtonLayout);
        logoutButtonLayout.setHorizontalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutButtonLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logoutButtonLayout.setVerticalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        header.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 40, 40));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        rentabilidadeButton.setBackground(header.getBackground());
        rentabilidadeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rentabilidadeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rentabilidadeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rentabilidadeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rentabilidadeButtonMouseExited(evt);
            }
        });
        rentabilidadeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentabilidadeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentabilidadeB.png"))); // NOI18N
        rentabilidadeIcon.setText("jLabel1");
        rentabilidadeButton.add(rentabilidadeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        rentabilidadeTxt.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        rentabilidadeTxt.setForeground(new java.awt.Color(255, 255, 255));
        rentabilidadeTxt.setText("Rentabilidade");
        rentabilidadeButton.add(rentabilidadeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        background.add(rentabilidadeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 160, 150, 190));

        estoqueButton.setBackground(header.getBackground());
        estoqueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estoqueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estoqueButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estoqueButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estoqueButtonMouseExited(evt);
            }
        });
        estoqueButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estoqueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estoqueB.png"))); // NOI18N
        estoqueIcon.setText("jLabel1");
        estoqueButton.add(estoqueIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        estoqueTxt.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        estoqueTxt.setForeground(new java.awt.Color(255, 255, 255));
        estoqueTxt.setText("Estoque");
        estoqueButton.add(estoqueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, -1, -1));

        background.add(estoqueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 160, 150, 190));

        funcionariosButton.setBackground(header.getBackground());
        funcionariosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        funcionariosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariosButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionariosButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionariosButtonMouseExited(evt);
            }
        });
        funcionariosButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcionariosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funcionariosB.png"))); // NOI18N
        funcionariosIcon.setText("jLabel1");
        funcionariosButton.add(funcionariosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        funcionariosTxt.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        funcionariosTxt.setForeground(new java.awt.Color(255, 255, 255));
        funcionariosTxt.setText("Funcionários");
        funcionariosButton.add(funcionariosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 150, -1, -1));

        background.add(funcionariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 160, 150, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_headerMouseDragged

    private void fecharTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseEntered
        fecharButton.setBackground(background.getBackground());
        fecharTxt.setForeground(header.getBackground());
    }//GEN-LAST:event_fecharTxtMouseEntered

    private void fecharTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseExited
        fecharButton.setBackground(header.getBackground());
        fecharTxt.setForeground(background.getBackground());
    }//GEN-LAST:event_fecharTxtMouseExited

    private void fecharTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_fecharTxtMouseClicked

    private void estoqueButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueButtonMouseEntered
        estoqueButton.setBackground(new Color(119, 34, 51));
    }//GEN-LAST:event_estoqueButtonMouseEntered

    private void estoqueButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueButtonMouseExited
        estoqueButton.setBackground(header.getBackground());
    }//GEN-LAST:event_estoqueButtonMouseExited

    private void funcionariosButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosButtonMouseEntered
        funcionariosButton.setBackground(new Color(119, 34, 51));
    }//GEN-LAST:event_funcionariosButtonMouseEntered

    private void funcionariosButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosButtonMouseExited
        funcionariosButton.setBackground(header.getBackground());
    }//GEN-LAST:event_funcionariosButtonMouseExited

    private void rentabilidadeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentabilidadeButtonMouseEntered
        rentabilidadeButton.setBackground(new Color(119, 34, 51));
    }//GEN-LAST:event_rentabilidadeButtonMouseEntered

    private void rentabilidadeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentabilidadeButtonMouseExited
        rentabilidadeButton.setBackground(header.getBackground());
    }//GEN-LAST:event_rentabilidadeButtonMouseExited

    private void estoqueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueButtonMouseClicked
        Estoque e = new Estoque();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
        e.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_estoqueButtonMouseClicked

    private void funcionariosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosButtonMouseClicked
        Funcionarios f = new Funcionarios();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_funcionariosButtonMouseClicked

    private void rentabilidadeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentabilidadeButtonMouseClicked
        Rentabilidade r = new Rentabilidade();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_rentabilidadeButtonMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Login l = new Login();
        l.setVisible(true);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel estoqueButton;
    private javax.swing.JLabel estoqueIcon;
    private javax.swing.JLabel estoqueTxt;
    private javax.swing.JPanel fecharButton;
    private javax.swing.JLabel fecharTxt;
    private javax.swing.JPanel funcionariosButton;
    private javax.swing.JLabel funcionariosIcon;
    private javax.swing.JLabel funcionariosTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoutButton;
    private javax.swing.JLabel nomeIcone;
    private javax.swing.JPanel rentabilidadeButton;
    private javax.swing.JLabel rentabilidadeIcon;
    private javax.swing.JLabel rentabilidadeTxt;
    // End of variables declaration//GEN-END:variables
}
