/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.villabeef.view;

//Janela modelo para desenvolvimento das interfaces

import com.villabeef.model.service.ManterEstoque;
import com.villabeef.model.service.ManterFuncionario;
import com.villabeef.model.service.ManterRentabilidade;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;


public class RegistroCompra extends javax.swing.JDialog {
    
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    
    
    /**
     * Creates new form Funcionarios1
     */
    public RegistroCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        dataCampo.setText(formato.format(Date.valueOf(LocalDate.now())));
        
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
    private int mouseX, mouseY;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        nomeIcone = new javax.swing.JLabel();
        fecharButton = new javax.swing.JPanel();
        fecharTxt = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        descricaoCampo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        data = new javax.swing.JLabel();
        dataCampo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        valor = new javax.swing.JLabel();
        valorCampo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cadastrarButton = new javax.swing.JPanel();
        cadastrarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(536, 380));
        setMinimumSize(new java.awt.Dimension(536, 380));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(536, 380));
        setResizable(false);

        background.setBackground(new java.awt.Color(245, 222, 179));
        background.setMaximumSize(new java.awt.Dimension(536, 380));
        background.setMinimumSize(new java.awt.Dimension(536, 380));
        background.setPreferredSize(new java.awt.Dimension(536, 380));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(76, 21, 32));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VILLAsmall.png"))); // NOI18N
        nomeIcone.setText("jLabel2");
        header.add(nomeIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, 100, -1));

        fecharButton.setBackground(header.getBackground());

        fecharTxt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fecharTxt.setForeground(background.getBackground());
        fecharTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecharTxt.setText("X");
        fecharTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        fecharTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        fecharTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fecharTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fecharTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout fecharButtonLayout = new javax.swing.GroupLayout(fecharButton);
        fecharButton.setLayout(fecharButtonLayout);
        fecharButtonLayout.setHorizontalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fecharButtonLayout.setVerticalGroup(
            fecharButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecharButtonLayout.createSequentialGroup()
                .addComponent(fecharTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        header.add(fecharButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        descricao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricao.setForeground(header.getBackground());
        descricao.setText("DESCRIÇÃO");
        background.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        descricaoCampo.setBackground(background.getBackground());
        descricaoCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descricaoCampo.setForeground(java.awt.Color.gray);
        descricaoCampo.setText("Insira os dados");
        descricaoCampo.setToolTipText("");
        descricaoCampo.setBorder(null);
        descricaoCampo.setDisabledTextColor(java.awt.Color.gray);
        descricaoCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descricaoCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descricaoCampoFocusLost(evt);
            }
        });
        descricaoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoCampoActionPerformed(evt);
            }
        });
        background.add(descricaoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 320, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 320, 10));

        data.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        data.setForeground(header.getBackground());
        data.setText("DATA");
        background.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        dataCampo.setBackground(background.getBackground());
        dataCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dataCampo.setForeground(java.awt.Color.gray);
        dataCampo.setText("Insira os dados");
        dataCampo.setToolTipText("");
        dataCampo.setBorder(null);
        dataCampo.setDisabledTextColor(java.awt.Color.gray);
        dataCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataCampoFocusLost(evt);
            }
        });
        background.add(dataCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 320, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 320, 10));

        valor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valor.setForeground(header.getBackground());
        valor.setText("VALOR");
        background.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        valorCampo.setBackground(background.getBackground());
        valorCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valorCampo.setForeground(java.awt.Color.gray);
        valorCampo.setText("Insira os dados");
        valorCampo.setToolTipText("");
        valorCampo.setBorder(null);
        valorCampo.setDisabledTextColor(java.awt.Color.gray);
        valorCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorCampoFocusLost(evt);
            }
        });
        background.add(valorCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 320, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 320, 10));

        cadastrarButton.setBackground(header.getBackground());

        cadastrarTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarTxt.setText("CADASTRAR");
        cadastrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cadastrarButtonLayout = new javax.swing.GroupLayout(cadastrarButton);
        cadastrarButton.setLayout(cadastrarButtonLayout);
        cadastrarButtonLayout.setHorizontalGroup(
            cadastrarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        cadastrarButtonLayout.setVerticalGroup(
            cadastrarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        background.add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseClicked
        doClose(RET_CANCEL);
    }//GEN-LAST:event_fecharTxtMouseClicked

    private void fecharTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseEntered
        fecharButton.setBackground(background.getBackground());
        fecharTxt.setForeground(header.getBackground());
    }//GEN-LAST:event_fecharTxtMouseEntered

    private void fecharTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharTxtMouseExited
        fecharButton.setBackground(header.getBackground());
        fecharTxt.setForeground(background.getBackground());
    }//GEN-LAST:event_fecharTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void descricaoCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoCampoFocusGained
        if(descricaoCampo.getText().equals("Insira os dados")) {
            descricaoCampo.setText("");
            descricaoCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_descricaoCampoFocusGained

    private void descricaoCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoCampoFocusLost
        if(descricaoCampo.getText().isBlank()) {
            descricaoCampo.setText("Insira os dados");
            descricaoCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_descricaoCampoFocusLost

    private void dataCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCampoFocusGained
        if(dataCampo.getText().equals("Insira os dados")) {
            dataCampo.setText("");
            dataCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_dataCampoFocusGained

    private void dataCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCampoFocusLost
        if(dataCampo.getText().isBlank()) {
            dataCampo.setText("Insira os dados");
            dataCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_dataCampoFocusLost

    private void valorCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorCampoFocusGained
        if(valorCampo.getText().equals("Insira os dados")) {
            valorCampo.setText("");
            valorCampo.setForeground(Color.black);
        }
    }//GEN-LAST:event_valorCampoFocusGained

    private void valorCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorCampoFocusLost
        if(valorCampo.getText().isBlank()) {
            valorCampo.setText("Insira os dados");
            valorCampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_valorCampoFocusLost

    private void cadastrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarTxtMouseClicked
        doClose(RET_OK);
    }//GEN-LAST:event_cadastrarTxtMouseClicked

    private void descricaoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoCampoActionPerformed

    private void cadastrarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarTxtMouseEntered
        cadastrarButton.setBackground(new Color(119, 34, 51));
    }//GEN-LAST:event_cadastrarTxtMouseEntered

    private void cadastrarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarTxtMouseExited
        cadastrarButton.setBackground(header.getBackground());
    }//GEN-LAST:event_cadastrarTxtMouseExited
    
    
    private void doClose(int retStatus) {
        try {
            if (retStatus == RET_OK) {
                String data = dataCampo.getText();
                String descricao = descricaoCampo.getText();
                double valor = Double.valueOf(valorCampo.getText().replace(',', '.'));
                
                ManterRentabilidade.inserir(data, 's', descricao, valor);
            }
            returnStatus = retStatus;
            setVisible(false);
            dispose();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getLocalizedMessage(), "Falha na conexão com o banco de dados.", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro inesperado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel cadastrarButton;
    private javax.swing.JLabel cadastrarTxt;
    private javax.swing.JLabel data;
    private javax.swing.JTextField dataCampo;
    private javax.swing.JLabel descricao;
    private javax.swing.JTextField descricaoCampo;
    private javax.swing.JPanel fecharButton;
    private javax.swing.JLabel fecharTxt;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nomeIcone;
    private javax.swing.JLabel valor;
    private javax.swing.JTextField valorCampo;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
